version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: passwd
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    environment:
      - ORCID_KEY=${ORCID_KEY}
      - ORCID_SECRET=${ORCID_SECRET}
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
