version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: passwd
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -u puma -b 'ssl://0.0.0.0:3000?key=private.key&cert=certificate.crt'
    environment:
      - ORCID_KEY=${ORCID_KEY}
      - ORCID_SECRET=${ORCID_SECRET}
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
