default: &default
  adapter: postgresql
  encoding: unicode
  port: <%= ENV['BOXEN_POSTGRESQL_PORT'] || 5432 %>
  host: localhost

development:
  <<: *default
  database: joss_development

test:
  <<: *default
  database: joss_test

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['HEROKU_POSTGRESQL_VIOLET_URL'] %>
