default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: passwd
  pool: 5

development:
  <<: *default
  database: uwc_development

test:
  <<: *default
  database: uwc_test

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
