# Changing this file necessitates a server restart
name: "Underworld Community"
abbreviation: "UWC"
issn: "0000-0000"
tagline: "a <strong>user friendly</strong> community for numerical models."
logo_url: "https://underworld-community.herokuapp.com/logo_large.png"
url: "https://underworld-community.herokuapp.com/"
editor_email: "romain@rbeucher.com"
noreply_email: "romain@rbeucher.com"
twitter: "@underworldcode"
google_analytics: "00-0000-00"
github: "underworld-community/uwc"
reviews: "underworld-community/uwc-reviews-testing"
models_repo: "underworld-community/uwc-models-testing"
models_html_url: "https://underworld-community.herokuapp.com/uwc-models"
product: "model" # the *thing* being submitted for review
reviewers: "https://bit.ly/2XC2Z9e"
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your model, its research application and any questions you have about the UWC submission criteria.
model_types: []
