# Changing this file necessitates a server restart
name: "ACCESS-MED Portal"
abbreviation: "MED Portal"
issn: "0000-0000"
tagline: "a <strong>catalog</strong> of model evaluation recipes."
logo_url: ""
url: "https://0.0.0.0:3000"
editor_email: "romain.beucher@anu.edu.au"
noreply_email: "romain.beucher@anu.edu.au"
twitter: "@access-nri"
google_analytics: "00-0000-00"
github: "ACCESS-MED/MED-Portal"
reviews: "ACCESS-MED/med-reviews-testing"
models_repo: "ACCESS-MED/med-recipes-testing"
models_html_url: ""
product: "recipe" # the *thing* being submitted for review
reviewers: ""
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your recipe, its research application and any questions you have about the MED-Portal submission criteria.
model_types: []
