# Changing this file necessitates a server restart
name: "ACCESS-MED Portal"
abbreviation: "MED Portal"
issn: "0000-0000"
tagline: "a <strong>catalog</strong> of model evaluation recipes."
logo_url: "https://medportal.herokuapp.com/logo_large.png"
url: "https://medportal.herokuapp.com/"
editor_email: "romain.beucher@anu.edu.au"
noreply_email: "romain.beucher@anu.edu.au"
twitter: "@access-nri"
google_analytics: "00-0000-00"
github: "ACCESS-MED/MED-Portal"
reviews: "ACCESS-MED/med-reviews"
models_repo: "ACCESS-MED/med-recipes"
models_html_url: "https://medportal.herokuapp.com/models"
product: "recipe" # the *thing* being submitted for review
reviewers: "https://docs.google.com/spreadsheets/d/1z7FXwP5HfsxfIcM7SypxkYYWC8YCrV_lNdg9TJMAbx8/edit?usp=sharing"
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your recipe, its research application and any questions you have about the MED-Portal submission criteria.
model_types: []
